-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.a_b_test_variants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  test_id uuid NOT NULL,
  post_id uuid NOT NULL,
  variant_name character varying,
  variant_number integer,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT a_b_test_variants_pkey PRIMARY KEY (id),
  CONSTRAINT a_b_test_variants_test_id_fkey FOREIGN KEY (test_id) REFERENCES public.a_b_tests(id),
  CONSTRAINT a_b_test_variants_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);
CREATE TABLE public.a_b_tests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  campaign_id uuid,
  name character varying NOT NULL,
  description text,
  status character varying DEFAULT 'draft'::character varying,
  test_type character varying,
  hypothesis text,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT a_b_tests_pkey PRIMARY KEY (id),
  CONSTRAINT a_b_tests_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT a_b_tests_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT a_b_tests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id uuid,
  details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.approvals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  requested_by uuid NOT NULL,
  approved_by uuid,
  status USER-DEFINED DEFAULT 'pending'::approval_status,
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT approvals_pkey PRIMARY KEY (id),
  CONSTRAINT approvals_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT approvals_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT approvals_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id),
  CONSTRAINT approvals_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.campaign_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  metric_date date NOT NULL,
  platform USER-DEFINED,
  total_posts integer DEFAULT 0,
  published_posts integer DEFAULT 0,
  total_impressions bigint DEFAULT 0,
  total_engagement integer DEFAULT 0,
  total_reach bigint DEFAULT 0,
  average_engagement_rate numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT campaign_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_analytics_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_analytics_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  goal text,
  status character varying DEFAULT 'active'::character varying,
  color text DEFAULT '#3B82F6'::text,
  icon character varying,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  content_themes ARRAY,
  target_audience jsonb DEFAULT '{}'::jsonb,
  performance_targets jsonb DEFAULT '{}'::jsonb,
  budget_hours integer DEFAULT 0,
  tags ARRAY,
  assigned_to ARRAY,
  is_archived boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  campaign_type text,
  goals ARRAY DEFAULT '{}'::text[],
  archived boolean DEFAULT false,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.content_threads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  title character varying,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT content_threads_pkey PRIMARY KEY (id),
  CONSTRAINT content_threads_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT content_threads_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.credential_audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  user_id uuid,
  platform USER-DEFINED NOT NULL,
  action character varying NOT NULL,
  status character varying NOT NULL,
  error_message text,
  error_code character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credential_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT credential_audit_log_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT credential_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.media_assets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  type USER-DEFINED NOT NULL,
  source USER-DEFINED DEFAULT 'uploaded'::media_source,
  url text NOT NULL,
  file_url character varying,
  thumbnail_url text,
  size bigint NOT NULL,
  file_size integer,
  width integer,
  height integer,
  duration_seconds integer,
  tags ARRAY DEFAULT '{}'::text[],
  alt_text character varying,
  usage_count integer DEFAULT 0,
  last_used_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT media_assets_pkey PRIMARY KEY (id),
  CONSTRAINT media_assets_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT media_assets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.oauth_states (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  platform USER-DEFINED NOT NULL,
  state character varying NOT NULL UNIQUE,
  code_challenge character varying,
  code_challenge_method character varying,
  ip_address character varying,
  user_agent text,
  is_used boolean DEFAULT false,
  used_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT oauth_states_pkey PRIMARY KEY (id),
  CONSTRAINT oauth_states_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id)
);
CREATE TABLE public.post_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  platform USER-DEFINED NOT NULL,
  impressions integer DEFAULT 0,
  reach integer DEFAULT 0,
  engagement_rate numeric DEFAULT 0,
  clicks integer DEFAULT 0,
  shares integer DEFAULT 0,
  comments integer DEFAULT 0,
  likes integer DEFAULT 0,
  reposts integer DEFAULT 0,
  replies integer DEFAULT 0,
  saves integer DEFAULT 0,
  engagement_total integer DEFAULT 0,
  engagement integer DEFAULT 0,
  fetched_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT post_analytics_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT post_analytics_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id)
);
CREATE TABLE public.post_content (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  text_content text,
  description text,
  hashtags ARRAY,
  mentions ARRAY,
  call_to_action character varying,
  version_number integer NOT NULL,
  change_summary text,
  changed_by uuid,
  is_current boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_content_pkey PRIMARY KEY (id),
  CONSTRAINT post_content_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT post_content_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.post_library (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  original_post_id uuid,
  title character varying,
  topic character varying,
  post_type character varying,
  platforms ARRAY,
  content jsonb,
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  platform_data jsonb,
  metrics jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_library_pkey PRIMARY KEY (id),
  CONSTRAINT post_library_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT post_library_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.post_media (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  media_asset_id uuid NOT NULL,
  position_order integer DEFAULT 0,
  usage_caption text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_media_pkey PRIMARY KEY (id),
  CONSTRAINT post_media_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT post_media_media_asset_id_fkey FOREIGN KEY (media_asset_id) REFERENCES public.media_assets(id)
);
CREATE TABLE public.post_platforms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  platform USER-DEFINED NOT NULL,
  platform_post_id character varying,
  platform_status character varying,
  platform_error_message text,
  platform_impressions integer DEFAULT 0,
  platform_engagement integer DEFAULT 0,
  platform_reach integer DEFAULT 0,
  posted_at timestamp with time zone,
  error_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_platforms_pkey PRIMARY KEY (id),
  CONSTRAINT post_platforms_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id)
);
CREATE TABLE public.posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  created_by uuid NOT NULL,
  campaign_id uuid,
  title character varying,
  topic text NOT NULL,
  post_type character varying DEFAULT 'post'::character varying,
  platforms ARRAY,
  content jsonb NOT NULL DEFAULT '{}'::jsonb,
  platform_templates jsonb DEFAULT '{}'::jsonb,
  status USER-DEFINED DEFAULT 'draft'::post_status,
  scheduled_at timestamp with time zone,
  published_at timestamp with time zone,
  engagement_score integer,
  engagement_suggestions ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT posts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT posts_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.social_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  platform USER-DEFINED NOT NULL,
  credentials_encrypted text NOT NULL,
  refresh_token_encrypted character varying,
  username character varying,
  account_id character varying,
  account_name character varying,
  profile_picture_url character varying,
  is_connected boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  connected_at timestamp with time zone,
  last_verified_at timestamp with time zone,
  access_token_expires_at timestamp with time zone,
  last_refreshed_at timestamp with time zone,
  refresh_error_count integer DEFAULT 0,
  last_error_message text,
  platform_user_id character varying,
  page_id character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  page_name character varying,
  expires_at timestamp with time zone,
  CONSTRAINT social_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT social_accounts_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  email text NOT NULL,
  full_name text,
  role USER-DEFINED NOT NULL DEFAULT 'viewer'::user_role,
  avatar_url text,
  phone character varying,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id)
);
CREATE TABLE public.workspace_invites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid NOT NULL,
  email character varying NOT NULL,
  invited_by uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'viewer'::user_role,
  token character varying NOT NULL UNIQUE,
  is_accepted boolean DEFAULT false,
  accepted_at timestamp with time zone,
  accepted_by_user_id uuid,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  used_at timestamp with time zone,
  CONSTRAINT workspace_invites_pkey PRIMARY KEY (id),
  CONSTRAINT workspace_invites_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT workspace_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id),
  CONSTRAINT workspace_invites_accepted_by_user_id_fkey FOREIGN KEY (accepted_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.workspaces (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  logo_url character varying,
  max_users integer DEFAULT 10,
  settings jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workspaces_pkey PRIMARY KEY (id)
);